#!/bin/bash

PORT=/dev/ttyUSB0
BOARD=esp8266:esp8266:d1_mini_clone

arduino-cli core install esp8266:esp8266 \
  --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
arduino-cli -v compile --fqbn "${BOARD}"
arduino-cli -v upload --fqbn "${BOARD}" -p "${PORT}"
